services:
  transcendence:
    build:
      context: docker
      dockerfile: transcendence
    volumes:
      - .:/app
      - assets:/app/assets/avatar
    ports:
      - "8443:8443"
      - "8000:8000"
    depends_on:
      - pong-server
    environment:
      - HOST_IP_ADDRESS
  pong-server:
    volumes:
      - .:/app
    build:
      context: docker
      dockerfile: pong-server
    ports:
      - "4210:4210"
  bonk-server:
    volumes:
      - .:/app
    build:
      context: docker
      dockerfile: bonk-server
    ports:
      - "9999:9999" # do we really have to expose the ports?
                    # they are proxied by caddy...

volumes:
  assets:
