# Generated by Django 5.0.4 on 2024-06-03 10:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ponk", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="current_room",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tournament_host",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
