# Generated by Django 5.0.4 on 2024-06-02 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ponk", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="BonkEvent",
        ),
        migrations.RemoveField(
            model_name="user",
            name="bonk_token",
        ),
    ]
