# Generated by Django 5.0.4 on 2024-06-03 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ponk", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="current_room",
            field=models.CharField(blank=True, default="", max_length=150),
        ),
    ]
