# Generated by Django 5.0.4 on 2024-06-05 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ponk", "0002_delete_bonkevent_remove_user_bonk_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="image",
            field=models.ImageField(upload_to="assets/avatars/"),
        ),
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.URLField(default="/assets/sheldon.png"),
        ),
    ]
