# Generated by Django 5.0.4 on 2024-05-20 00:11

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ponk", "0002_shopitems_remove_user_display_name_user_avatar_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="skins",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(), default=[], size=None
            ),
            preserve_default=False,
        ),
    ]
