# Generated by Django 5.0.4 on 2024-05-22 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ponk", "0003_user_skins"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="auth",
            field=models.IntegerField(choices=[(1, "Basic"), (2, "Ft")], default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, verbose_name="email address"
            ),
        ),
    ]
