# Generated by Django 5.0.4 on 2024-05-22 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ponk", "0004_user_auth_alter_user_email"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="auth",
            new_name="auth_method",
        ),
    ]
