# Generated by Django 5.0.4 on 2024-05-22 22:37

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ponk", "0006_alter_user_avatar_alter_user_level_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="skins",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(), default=[], size=None
            ),
        ),
    ]
