# Generated by Django 5.0.4 on 2024-05-23 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ponk", "0008_alter_user_skins"),
    ]

    operations = [
        migrations.AddField(
            model_name="gamehistory",
            name="xp",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
