# Generated by Django 5.0.4 on 2024-05-25 14:53

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ponk", "0009_user_selected_skin"),
    ]

    operations = [
        migrations.CreateModel(
            name="BonkEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("game_id", models.PositiveIntegerField(default=0)),
                (
                    "users",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(), size=None
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="user",
            name="selected_skin",
            field=models.CharField(default=""),
        ),
    ]
