# Generated by Django 5.0.4 on 2024-05-25 15:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ponk", "0010_bonkevent_alter_user_selected_skin"),
    ]

    operations = [
        migrations.AddField(
            model_name="bonkevent",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
