# Generated by Django 5.0.4 on 2024-05-26 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ponk", "0011_bonkevent_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="bonk_token",
            field=models.CharField(default=""),
        ),
    ]
