# Generated by Django 5.0.4 on 2024-05-26 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ponk", "0013_remove_user_bonk_token"),
    ]

    operations = [
        migrations.DeleteModel(
            name="BonkEvent",
        ),
    ]
