# Generated by Django 5.0.4 on 2024-05-27 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ponk", "0010_user_citation_alter_user_selected_skin"),
        ("ponk", "0010_user_last_online_alter_user_selected_skin"),
        ("ponk", "0014_delete_bonkevent"),
    ]

    operations = []
