#!/bin/sh

export SHELL=zsh
export PS1="[1mBonk Corporation[0m %% "
export "PATH=venv/bin/:$PATH"
export PIP_DISABLE_PIP_VERSION_CHECK=1
export NIX_IGNORE_SYMLINK_STORE=1
export NIX_ENFORCE_PURITY=0
export PGDATA="backend/.pg"
export UV_USE_IO_URING=0
export TERM=xterm
