#!/bin/sh

prod=$1

make venv

if [ "$prod" = true ]; then
	# in docker
	sed -i '1s|.*|#!/app/venv/bin/python3|' venv/bin/pip3
else
	sed -i "1s|.*|#!$PWD/venv/bin/python3|" venv/bin/pip3
fi

source venv/bin/activate

pip3 install -r requirements.txt --break-system-packages
