#!/bin/sh

prod=$1

if [ "$prod" = true ]; then
	export "optional_https_url=,\ https://localhost:8443"
fi

export "srv_root=$PWD/.static"
export "skins_root=$PWD/skins"
export "media_root=$PWD/backend/media"

# copy all static files to .static, to be served by caddy
# since serving them by django is strongly discouraged
yes yes | python backend/manage.py collectstatic

caddy start --adapter caddyfile --config <( cat <<-EOF
	{
		auto_https disable_redirects
	}

	http://$HOST_IP_ADDRESS:8000$optional_https_url

	handle_path /static/* {
		root * $srv_root
		file_server
	}

	handle_path /skins/* {
		root * $skins_root
		file_server
	}

	handle_path /media/* {
		root * $media_root
		file_server
	}

	handle {
		reverse_proxy localhost:8001 # django
		header {
			Server bob
		}
	}
EOF
)
