#!/bin/sh

prod=$1

if [ "$prod" = true ]; then
	export "optional_https_url=,\ https://localhost:8443"
fi

export "srv_root=$PWD/.static"
export "assets_root=$PWD/assets"

export "pong_upstream=localhost"
export "bonk_upstream=localhost"
if [ -f /.dockerenv ]; then
	export "pong_upstream=pong-server"
	export "bonk_upstream=bonk-server"
fi

rm -rf .static
# copy all static files to .static, to be served by caddy
# since serving them by django is strongly discouraged
yes yes | python backend/manage.py collectstatic

caddy start --adapter caddyfile --config <( cat <<-EOF
	{
		auto_https disable_redirects
	}

	http://$HOST_IP_ADDRESS:8000$optional_https_url

	handle_path /static/* {
		root * $srv_root
		file_server
		header {
			Cross-Origin-Opener-Policy same-origin
			Cross-Origin-Embedder-Policy require-corp
		}
	}

	handle_path /assets/* {
		root * $assets_root
		file_server
	}

	handle {
		header /bonk {
			Cross-Origin-Opener-Policy same-origin
			Cross-Origin-Embedder-Policy require-corp
		}
		reverse_proxy localhost:8001 # django
		header {
			Server bob
		}
	}

	handle_path /pong-ws {
		reverse_proxy $pong_upstream:4210
	}

	handle_path /bonk-ws {
		reverse_proxy $bonk_upstream:9999
	}
EOF
)
